name: Build, Test and Release

on:
  push:
    branches:
      - master
  release:
    types:
    - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: xvfb-run -a npm test
    - run: npm install vsce --save-dev
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/releases/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
